apiVersion: apps/v1
kind: Deployment
metadata:
  name: centralized-logging
  labels:
    app: centralized-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centralized-logging
  template:
    metadata:
      labels:
        app: centralized-logging
    spec:
      containers:
      - name: centralized-logging
        image: centralized-logging:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: centralized-logging
spec:
  selector:
    app: centralized-logging
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
